spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:\Users\HP\Desktop\ocochodzi\Ocochodzi\dbtest'
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create