 spring:
     h2.console:
       enabled: true
       path: '/console'
     main:
       banner-mode: off
     datasource:
       url: jdbc:h2:mem:testdb
       driver-class-name: org.h2.Driver
       username: sa
       password:
     jpa.hibernate:
       ddl-auto: create-drop
 Products.allowToMultipleProductsFromTemplate: false